### ISSUE TITLE
No translation possible

### ISSUE THREAD

**Issue by ralf-krause** [jguille2/moodle-assignsubmission_snap#3]
Hi,
I wanted to translate the plugin moodle-assignsubmission_snap into german language so also german users will get the plugin in their language. I could not find the plugin in AMOS https://lang.moodle.org/local/amos/ .
Best regards
Ralf

Ralf Krause
moodleSCHULE e.V.

**Comment by jguille2** [comment]
Hi Ralf!

I am seeing that I have to do some management for the plugin to be in AMOS. I try to fix it as soon as possible.
I will report it in this thread...

Thanks,
Joan

**Comment by jguille2** [comment]
Hi Ralf!

I think this issue is fixed. I've changed some strings (you will see I've released 2.2 version, is just for this) and now I see Snap! plugin in AMOS, ready to translate.

Tell me any problem (with translation or with the plugin itself) and I'll be happy to help you... Thanks for the interest and it will be great to have the German version (you know there are many German snappers!)

Joan

**Comment by ralf-krause** [comment]
The plugin is translated for the german language pack. I will try the plugin in one of my Moodle platforms to look at the strings and their functions.
Ralf
