### ISSUE TITLE
Snap! appears in English with child language packs

### ISSUE THREAD

**Issue by ralf-krause** [jguille2/moodle-assignsubmission_snap#4]
Hi Joan,
the Snap! language appears in English even the Moodle language is set to de_du or de_kids. Yes, when I set the Moodle course to the language pack de then I get a German Snap! with German programming blocks but not with the language packs de_du and de_kids. The Snap! language must also work with the child packages de_du, de_kids, de_ch, de_comm, de_wp. 

I am a maintainer for the German language packs. I hope you will fix this problem as soon as possible because the packages de_du and de_kids are used in Moodle for students in primary and secondary schools. The package de is used with a formal salutation for persons which is not used for the salutation for younger students  and well known persons.

Please look also to https://tracker.moodle.org/browse/MDL-77361 and https://tracker.moodle.org/browse/MDL-71050.

Kind regards,
Ralf

**Comment by ralf-krause** [comment]
![moodle-snap-language](https://user-images.githubusercontent.com/27956839/227208925-4ff37597-9885-4f25-8983-7e62798a8c49.png)

**Comment by jguille2** [comment]
Hi Ralf.

Uf! I've never heard anything about child language packs!

And I see the problem... but I am doubting which is the best solution...

Our problem is
https://snap.berkeley.edu/snap/snap.html#run:noRun&editMode&lang=de is right
but
https://snap.berkeley.edu/snap/snap.html#run:noRun&editMode&lang=de_kids
because Snap! doesn't know anything about that "de_kids" language.

If I cut those "sublang" strings other langs will have problems, because we have some "Snap lang packs" like "pt_BR", "zh_CN", "zh_TW"...

Now I'm thinking on two possible solutions:
  - One is in the Snap! side, and maybe is the better solution. If there is no "xx_yy" lang translation, try "xx" translation. This solution will fix our "URL problem" (for Moodle or for anything else). I talk to Jens Mönig to see his opinion about this.
  - And if the fist one is not possible... maybe I have to cut that "sublang string" when it is lowercase. I have to read about these standard names first.
Continue...

**Comment by jguille2** [comment]
Hi Ralf!

I've fixed our "lang features" in Snap! itself. Then, every request to a non existing "sub-lang" translation ("de_child" and even "de_CH" or "de_AT"), trys to load the "main" translation (in the example, "de").

This is fixed in the main Snap! repository but it is not the current release yet.
We have to wait to the next release (8.2.4 or 8.3... or 9,0?).
If it is too long (I don't know the times) for you, I can release a Snap4Arduino8.3 release to play with that fix.

Joan

**Comment by jguille2** [comment]
Hi Ralf!

I've fixed our "lang features" in Snap! itself. Then, every request to a non existing "sub-lang" translation ("de_child" and even "de_CH" or "de_AT"), trys to load the "main" translation (in the example, "de").

https://github.com/jmoenig/Snap/pull/3200#event-8851691550

This is fixed in the main Snap! repository but it is not the current (online) release yet.
We have to wait to the next release (8.2.4 or 8.3... or 9,0?).
If it is too long (I don't know the times) for you, I can release the Snap4Arduino8.3 release to play with that fix.

Joan

**Comment by ralf-krause** [comment]
Great! So I will install the new plugin version and then we have to wait for the Snap! update. Yes, I will also test Snap4Arduino.

I have an additional idea for the language setting. Currently a teacher can setup only the language from Snap! or the language from Moodle. I think it could be a good idea to allow the teachers to specify a language. So the teacher himself writes the language string into a field and if his string is incorrect he will get english. Or another idea he uses a dropdown menu with all Snap! languages.

Could it be possible to set a parameter which does not allow to change the language in Snap! itself? A teacher could have the idea that his students should program a project in Snap! with english blocks but the Moodle language is german or something else. Yes, I know ... the students can open a second browser tab with the Snap! outside of Moodle. 

Ralf

<img width="831" alt="Snap! plugin language setting" src="https://user-images.githubusercontent.com/27956839/227942984-e1501439-8592-495c-bf60-f4b3a0e84b51.png">

**Comment by jguille2** [comment]
Hi Ralf,

I will think about this... but:
- Snap! doesn't want (never) to block anything to students. We can hide blocks and customize many things... but they always can to unhide and change everything. The idea is to facilitate things (for example, creating microworlds) but never block features. It's that idea of "Low floor" but "No ceiling"
- In fact, you work in a project without a user, and so, without rols or permissions... And so, there is nothing you can do to block (only hide or use some "harder to find" features).

- About another lang field, to cutomize Snap!... I will think but now I don't see it well at first. I love Moodle... and all my discussions (with other teachers) is they find easier Classroom... because it has less options. For me, options is freedom... But we have to rationalize them and not overload the interface.
- Other Snappers think that current lang option is not necessary, because each user has recorded his preference... But did this in the same way Moodle can impose a language in a course. Then, for me, the most balanced option is that only when you impose a language in a course, you can "impose" (initially) that language as the starting point of the project.

Thanks Ralf! I appreciate your interest
If I see next Snap release is not soon... I will upload "somewhere" public the current state and then you could test...

Joan

**Comment by ralf-krause** [comment]
Thanks!

**Comment by jguille2** [comment]
Hi Ralf @ralf-krause 

You know Snap!9 will have that fix to accept those "sublang" requests ("de_kids", "de_AT"...)

Today I've released Snap4Arduino 8.2.4 and I've added to this version (still Snap! v8) this "lang fix" to be able to offer this solution already.
https://twitter.com/jguille2/status/1660817730227011584
I close this issue and you can test it, using https://snap4arduino.rocks/run/ as an Snap! distro inside the Moodle operation. It have to accept that "de_kids" and offer you  the current German translation.

Any problem... continue here. Remember that Snap/Snap4Arduino online versions are quite cached (as a Progressive Web App, to be able tu be run offline easily). Maybe you have to purge you cache mem...
